[2024-10-20T19:56:15.720+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T19:56:15.736+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: binance_data_extraction.load_data_to_redshift manual__2024-10-20T19:56:11.568491+00:00 [queued]>
[2024-10-20T19:56:15.744+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: binance_data_extraction.load_data_to_redshift manual__2024-10-20T19:56:11.568491+00:00 [queued]>
[2024-10-20T19:56:15.744+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-20T19:56:15.763+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data_to_redshift> on 2024-10-20 19:56:11.568491+00:00
[2024-10-20T19:56:15.773+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=188) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-20T19:56:15.775+0000] {standard_task_runner.py:72} INFO - Started process 190 to run task
[2024-10-20T19:56:15.778+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'binance_data_extraction', 'load_data_to_redshift', 'manual__2024-10-20T19:56:11.568491+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/binance_data_extraction.py', '--cfg-path', '/tmp/tmp0pcplovu']
[2024-10-20T19:56:15.780+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask load_data_to_redshift
[2024-10-20T19:56:15.828+0000] {task_command.py:467} INFO - Running <TaskInstance: binance_data_extraction.load_data_to_redshift manual__2024-10-20T19:56:11.568491+00:00 [running]> on host 3c6d286072f5
[2024-10-20T19:56:15.910+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='binance_data_extraction' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T19:56:11.568491+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T19:56:11.568491+00:00'
[2024-10-20T19:56:15.912+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-20T19:56:15.912+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-20T19:56:15.912+0000] {logging_mixin.py:190} INFO - Current task name:load_data_to_redshift state:running start_date:2024-10-20 19:56:15.736727+00:00
[2024-10-20T19:56:15.912+0000] {logging_mixin.py:190} INFO - Dag name:binance_data_extraction and current dag run status:running
[2024-10-20T19:56:15.912+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T19:56:18.444+0000] {logging_mixin.py:190} INFO - Conexi√≥n exitosa a Redshift
[2024-10-20T19:56:18.446+0000] {logging_mixin.py:190} INFO - Error al insertar o actualizar datos en Redshift: [Errno 2] No such file or directory: 'datos/binance_prices.csv'
[2024-10-20T19:56:18.447+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/binance_data_extraction.py", line 92, in load_data_to_redshift
    cursor.close()
    ^^^^^^
UnboundLocalError: cannot access local variable 'cursor' where it is not associated with a value
[2024-10-20T19:56:18.462+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-20T19:56:18.462+0000] {logging_mixin.py:190} INFO - Task start:2024-10-20 19:56:15.736727+00:00 end:2024-10-20 19:56:18.461594+00:00 duration:2.724867
[2024-10-20T19:56:18.462+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data_to_redshift> dag:<DAG: binance_data_extraction> dagrun:<DagRun binance_data_extraction @ 2024-10-20 19:56:11.568491+00:00: manual__2024-10-20T19:56:11.568491+00:00, state:running, queued_at: 2024-10-20 19:56:11.591090+00:00. externally triggered: True>
[2024-10-20T19:56:18.463+0000] {logging_mixin.py:190} INFO - Failure caused by cannot access local variable 'cursor' where it is not associated with a value
[2024-10-20T19:56:18.463+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=binance_data_extraction, task_id=load_data_to_redshift, run_id=manual__2024-10-20T19:56:11.568491+00:00, execution_date=20241020T195611, start_date=20241020T195615, end_date=20241020T195618
[2024-10-20T19:56:18.485+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T19:56:18.486+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task load_data_to_redshift (cannot access local variable 'cursor' where it is not associated with a value; 190)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/binance_data_extraction.py", line 92, in load_data_to_redshift
    cursor.close()
    ^^^^^^
UnboundLocalError: cannot access local variable 'cursor' where it is not associated with a value
[2024-10-20T19:56:18.515+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-20T19:56:18.535+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-20T19:56:18.536+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
